# Setup
title:               Resume
tagline:             'Portfolio & Resume'
description:         'Made by <a href="https://iiee0.github.io/resume" target="_blank">@jiunsuk</a>.'
url:                 'https://iiee0.github.io'
baseurl:             '/resume'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              석지운 
  url:               https://twitter.com/mdo
  email:             jiunsu2@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
