# Setup
title:               Resume
tagline:             'Portfolio & Resume'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://iiee0.github.io/portfolio/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              석지운 
  url:               https://twitter.com/mdo
  email:             jiunsu2@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
